name: UnitTests

on:
  push:
    branches:
      - main
  #   paths:
  #     - 'src/**'
  #     - 'tests/**'
  # pull_request:
  #   paths:
  #     - 'src/**'
  #     - 'tests/**'

jobs:
  Accounts_Unit_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Adjust to your Python version

      - name: Accounts - Install dependencies and test
        run: | 
          cd src
          cd Accounts
          pip install pytest
          pip install -r requirements.txt
          python -m pytest
      
      - name: Permissions - Install dependencies and test
        run: | 
          cd src
          cd Permissions
          pip install pytest
          pip install -r requirements.txt
          python -m pytest
      
      - name: Sessions - Install dependencies and test
        run: | 
          cd src
          cd Sessions
          pip install pytest
          pip install -r requirements.txt
          python -m pytest
      
